
# Name of the github Acrtions and workflow

name: CD
   
    # When should CD run workflow run ?

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed


# Jobs performed by cd workflow

jobs:
   deploy:

   # Runs CD only when CI Succeeds
    if: ${{ github.event.workflow_run.conclusion == 'success' }}


     runs-on: ubuntu-latest


  # Steps perfomed by the CD job
     steps:

    
      #First step: Verify CD Started
      - name : CD started
        run : echo "CI completd. CD workflow started"
