
# Name of the GitHub Actions workflow

name: CI

# When should this workflow run?
on:
  # Run whenever we push code
   push:
      # But only when pushing to the main branch
       branches:
         - main 

# Jobs are the main tasks performed by this workflow
jobs:

    # Name of our job
    test:
 
    # GitHub provides an Ubuntu virtual machine (runner)
       runs-on: ubuntu-latest

     # Individual tasks performed by the runner
       steps:
     
    # Step 1: Download/checkout our repository code
        - name: Checkout code
          uses: actions/checkout@v4

      # Step 2: Install Node.js on the runner
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20

      # Step 3: Check Node.js version
        
        - name: Check Node.js Version
          run: node --version

      # Step 4 : Install Dependencies
        - name: Install client dependencies
          run: npm install
          working-directory: ./client

     # Step 5: Build react client
        - name: Build client
          run: npm run build
          working-directory: ./client

    # Step 6: Install dependenices in server
        - name: Install Server Dependencies
          run: npm install
          working-directory: ./server

    # Step 7: Verify express server can be loaded
        - name: Check Server
          run: node --check src/index.js
          working-directory: ./server









# //// For my Understanding

  #     WORKFLOW
  #  │
  #  ├── Trigger → When should it run?
  #  │
  #  └── Jobs
  #       │
  #       └── Job → What work should happen?
  #            │
  #            ├── Runner → Where does it run?
  #            │
  #            └── Steps
  #                 ├── Checkout code
  #                 └── Run commands
